---
openapi: 3.0.0
info:
  title: Resale Challenge
  description: API de controle de Imobiliárias e Imóveis
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/gabrielcesar95/resale_challenge/1.0.0
  description: SwaggerHub API Auto Mocking
paths:
  /real-estates:
    get:
      summary: Adquire a listagem de imobiliárias
      responses:
        "200":
          description: Imobiliárias encontradas.
          content:
            application/json:
              schema:
                type: object
                properties:
                  real-estates:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 1
                        name:
                          type: string
                          example: Frias Neto
                        address:
                          type: string
                          example: Av. dos Operários, 587 - Cidade Jardim, Piracicaba - SP, 13416-460
    post:
      summary: Cadastra uma nova imobiliária
      requestBody:
        content:
          application/json:
            schema:
              required:
              - name
              properties:
                name:
                  type: string
                  example: Junqueira
                address:
                  type: string
                  example: R. Treze de Maio, 432 - Centro, Piracicaba - SP, 13400-300
        required: true
      responses:
        "200":
          description: Imobiliária cadastrada com sucesso.
          content:
            application/json:
              schema:
                type: object
                properties:
                  real-estate:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      name:
                        type: string
                        example: Junqueira
                      address:
                        type: string
                        example: R. Treze de Maio, 432 - Centro, Piracicaba - SP, 13400-300
        "400":
          description: Erro de validação
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: object
                    properties:
                      name:
                        type: string
                        example: Length must be between 1 and 120.
  /real-estates/{id}:
    get:
      summary: Adquire os dados da Imobiliária
      parameters:
      - name: id
        in: path
        description: ID da imobiliária
        required: true
        style: simple
        explode: false
        schema:
          type: integer
        example: 1
      responses:
        "200":
          description: Imobiliária encontrado.
          content:
            application/json:
              schema:
                type: object
                properties:
                  real-estate:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      name:
                        type: string
                        example: Junqueira
                      address:
                        type: string
                        example: R. Treze de Maio, 432 - Centro, Piracicaba - SP, 13400-300
        "404":
          description: Não encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: object
                    properties:
                      message:
                        type: string
                        example: Imobiliária não encontrada
    put:
      summary: Altera a imobiliária
      parameters:
      - name: id
        in: path
        description: ID da imobiliária
        required: true
        style: simple
        explode: false
        schema:
          type: integer
        example: 2
      requestBody:
        content:
          application/json:
            schema:
              properties:
                name:
                  type: string
                  example: Junqueira Imóveis
                address:
                  type: string
                  example: R. Treze de Maio, 433 - Centro, Piracicaba - SP, 13400-300
      responses:
        "200":
          description: Imobiliária alterada com sucesso.
          content:
            application/json:
              schema:
                type: object
                properties:
                  real-estate:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 2
                      name:
                        type: string
                        example: Junqueira Imóveis
                      address:
                        type: string
                        example: R. Treze de Maio, 433 - Centro, Piracicaba - SP, 13400-300     
        "400":
          description: Erro de validação
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: object
                    properties:
                      name:
                        type: string
                        example: Length must be between 1 and 120.
    delete:
      summary: Exclui a imobiliária
      parameters:
      - name: id
        in: path
        description: ID da imobiliária
        required: true
        style: simple
        explode: false
        schema:
          type: integer
        example: 1
      responses:
        "200":
          description: Imobiliária deletada com sucesso.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Imobiliária deletada
        "404":
          description: Imobiliária não encontrada
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Imobiliária não encontrada
  /properties:
    get:
      summary: Adquire a listagem de imóveis
      responses:
        "200":
          description: Imóveis encontrados.
          content:
            application/json:
              schema:
                type: object
                properties:
                  properties:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 1
                        name:
                          type: string
                          example: Apartamento em condomínio fechado
                        address:
                          type: string
                          example: Rua São João, 321 - Centro, Piracicaba - SP, 13416-585
                        description:
                          type: string
                          example: Lindo apartamento em local conveniente e seguro
                        status:
                          type: boolean
                          example: true
                        characteristics:
                          type: object
                          properties:
                            bathrooms:
                              type: integer
                              example: 2
                            bedrooms:
                              type: integer
                              example: 2
                            parking_spots:
                              type: integer
                              example: 1
                        type:
                          type: string
                          example: A
                        finality:
                          type: string
                          example: R
                        real_estate_id:
                          type: integer
                          example: 1

    post:
      summary: Cadastra um novo imóvel
      requestBody:
        content:
          application/json:
            schema:
              required:
              - name
              - address
              - description
              - status
              - type
              - real_estate_id
              properties:
                name:
                  type: string
                  example: Apartamento em condomínio fechado
                address:
                  type: string
                  example: Rua São João, 321 - Centro, Piracicaba - SP, 13416-585
                description:
                  type: string
                  example: Lindo apartamento em local conveniente e seguro
                status:
                  type: boolean
                  example: true
                characteristics:
                  type: object
                  properties:
                    bathrooms:
                      type: integer
                      example: 2
                    bedrooms:
                      type: integer
                      example: 2
                    parking_spots:
                      type: integer
                      example: 1
                type:
                  type: string
                  example: A
                finality:
                  type: string
                  example: R
                real_estate_id:
                  type: integer
                  example: 1
        required: true
      responses:
        "200":
          description: Imóvel cadastrado com sucesso.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  name:
                    type: string
                    example: Apartamento em condomínio fechado
                  address:
                    type: string
                    example: Rua São João, 321 - Centro, Piracicaba - SP, 13416-585
                  description:
                    type: string
                    example: Lindo apartamento em local conveniente e seguro
                  status:
                    type: boolean
                    example: true
                  characteristics:
                    type: object
                    properties:
                      bathrooms:
                        type: integer
                        example: 2
                      bedrooms:
                        type: integer
                        example: 2
                      parking_spots:
                        type: integer
                        example: 1
                  type:
                    type: string
                    example: A
                  finality:
                    type: string
                    example: R
                  real_estate_id:
                    type: integer
                    example: 1
        "400":
          description: Erro de validação
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: object
                    properties:
                      name:
                        type: string
                        example: Length must be between 1 and 120.
  /properties/{id}:
    get:
      summary: Adquire os dados do Imóvel
      parameters:
      - name: id
        in: path
        description: ID do imóvel
        required: true
        style: simple
        explode: false
        schema:
          type: integer
        example: 1
      responses:
        "200":
          description: Imobiliária encontrado.
          content:
            application/json:
              schema:
                type: object
                properties:
                  property:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      name:
                        type: string
                        example: Apartamento em condomínio fechado
                      address:
                        type: string
                        example: Rua São João, 321 - Centro, Piracicaba - SP, 13416-585
                      description:
                        type: string
                        example: Lindo apartamento em local conveniente e seguro
                      status:
                        type: boolean
                        example: true
                      characteristics:
                        type: object
                        properties:
                          bathrooms:
                            type: integer
                            example: 2
                          bedrooms:
                            type: integer
                            example: 2
                          parking_spots:
                            type: integer
                            example: 1
                      type:
                        type: string
                        example: A
                      finality:
                        type: string
                        example: R
                      real_estate_id:
                        type: integer
                        example: 1
        "404":
          description: Não encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: object
                    properties:
                      message:
                        type: string
                        example: Imóvel não encontrado
    put:
      summary: Altera o imóvel
      parameters:
      - name: id
        in: path
        description: ID do imóvel
        required: true
        style: simple
        explode: false
        schema:
          type: integer
        example: 2
      requestBody:
        content:
          application/json:
            schema:
              properties:
                name:
                  type: string
                  example: Apartamento em condomínio fechado
                address:
                  type: string
                  example: Rua São João, 321 - Centro, Piracicaba - SP, 13416-585
                description:
                  type: string
                  example: Lindo apartamento em local conveniente e seguro
                status:
                  type: boolean
                  example: true
                characteristics:
                  type: object
                  properties:
                    bathrooms:
                      type: integer
                      example: 2
                    bedrooms:
                      type: integer
                      example: 2
                    parking_spots:
                      type: integer
                      example: 1
                type:
                  type: string
                  example: A
                finality:
                  type: string
                  example: R
                real_estate_id:
                  type: integer
                  example: 1
      responses:
        "200":
          description: Imóvel alterado com sucesso.
          content:
            application/json:
              schema:
                type: object
                properties:
                  property:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      name:
                        type: string
                        example: Apartamento em condomínio fechado
                      address:
                        type: string
                        example: Rua São João, 321 - Centro, Piracicaba - SP, 13416-585
                      description:
                        type: string
                        example: Lindo apartamento em local conveniente e seguro
                      status:
                        type: boolean
                        example: true
                      characteristics:
                        type: object
                        properties:
                          bathrooms:
                            type: integer
                            example: 2
                          bedrooms:
                            type: integer
                            example: 2
                          parking_spots:
                            type: integer
                            example: 1
                      type:
                        type: string
                        example: A
                      finality:
                        type: string
                        example: R
                      real_estate_id:
                        type: integer
                        example: 1
        "400":
          description: Erro de validação
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: object
                    properties:
                      name:
                        type: string
                        example: Length must be between 1 and 120.
    delete:
      summary: Exclui o imóvel
      parameters:
      - name: id
        in: path
        description: ID do imóvel
        required: true
        style: simple
        explode: false
        schema:
          type: integer
        example: 1
      responses:
        "200":
          description: Imóvel deletado com sucesso.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Imóvel deletado
        "404":
          description: Imóvel não encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Imóvel não encontrado